const C = {
  SET_ALL_CAT: "SET_ALL_CAT",
  SELECT_CAT: "SELECT_CAT",
  SET_USER: "SET_USER",
  DEL_USER: "DEL_USER",
  SET_ALL_CONTACTS: "SET_ALL_CONTACTS",
  SET_FILTER_CONTACTS: "SET_FILTER_CONTACTS",
  ADD_CATEGORY: "ADD_CATEGORY",
  SET_GROUP_CONTACTS: "SET_GROUP_CONTACTS",
  SET_BIRTHDAY_DATA: "SET_BIRTHDAY_DATA",
  UPDATE_USER: "UPDATE_USER",
};

export default C;
